import type { Metadata } from "next";
import { Inter, Noto_Sans, Lato } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Provider from "@/context/Provider";
import LoadProvider from "@/context/LoadProvider";
import { Toaster } from "sonner";

const lato = Lato({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={`${lato.className} min-h-screen`}>
          <LoadProvider>
            <NavBar />
            {children}
            <Toaster richColors={true} closeButton={true} />
          </LoadProvider>
        </body>
      </Provider>
    </html>
  );
}
